name: Clone and Copy MD files

on:
  push:
    branches:
      - 0.3

jobs:
  clone-and-copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone remote repository
      run: |
        git clone https://github.com/walter-lkmx/respaldo-doc.git
      
    - name: Copy MD files
      run: |
        cp -R respaldo-doc/md-files/. pages/content

